name: Build & SonarCloud
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    env:
      SONAR_ORG: PeTkun_Industries
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v6

      - name: Build Laba1
        run: |
          rm -rf Laba1/build
          mkdir Laba1/build
          cmake -S Laba1 -B Laba1/build
          build-wrapper-linux-x86-64 --out-dir Laba1/build_wrapper make -C Laba1/build

      - name: SonarCloud scan Laba1
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=PeTkun_Industries_Laba1
            -Dsonar.organization=${{ env.SONAR_ORG }}
            -Dsonar.sources=Laba1
            -Dsonar.cfamily.compile-commands=Laba1/build_wrapper/compile_commands.json
            -Dsonar.coverage.exclusions=**
            -Dsonar.cfamily.skipCoverage=true

      - name: Build Laba2
        run: |
          rm -rf Laba2/build
          mkdir Laba2/build
          cmake -S Laba2 -B Laba2/build
          build-wrapper-linux-x86-64 --out-dir Laba2/build_wrapper make -C Laba2/build

      - name: SonarCloud scan Laba2
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=PeTkun_Industries_Laba2
            -Dsonar.organization=${{ env.SONAR_ORG }}
            -Dsonar.sources=Laba2
            -Dsonar.cfamily.compile-commands=Laba2/build_wrapper/compile_commands.json
            -Dsonar.coverage.exclusions=**
            -Dsonar.cfamily.skipCoverage=true
